name: OpenClawChat
options:
  bundleIdPrefix: ai.openclaw
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
packages:
  OpenClawWS:
    path: ../ios-openclaw-ws-mvp

targets:
  OpenClawChat:
    type: application
    platform: iOS
    sources:
      - path: OpenClawChat
    resources:
      - path: OpenClawChat/Assets.xcassets
    dependencies:
      - package: OpenClawWS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.openclaw.OpenClawChat
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_NSCameraUsageDescription: "Necesitamos la cámara para enviar imágenes al chat."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Necesitamos acceso a Fotos para seleccionar imágenes y enviarlas al chat."
        INFOPLIST_KEY_UIFileSharingEnabled: YES
        INFOPLIST_KEY_LSSupportsOpeningDocumentsInPlace: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: UAVT76BDCW
        TARGETED_DEVICE_FAMILY: "1"
